services:
  - name: maven-sample
    type: web
    runtime: java
    plan: free
    envVars:
      - key: PORT
        value: 8080
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/maven-sample-0.0.1-SNAPSHOT.jar"
